import { useState, useEffect } from "react";
import BaseModal from "../BaseModal";
import { FileJson } from "lucide-react";

interface TrackModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (trackJson: any) => Promise<void>;
  initialData?: any;
}

export default function TrackModal({ isOpen, onClose, onSubmit, initialData }: TrackModalProps) {
  const [jsonText, setJsonText] = useState("");
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        // Remove mongoose fields before editing
        const cleanedData = { ...initialData };
        delete cleanedData._id;
        delete cleanedData.createdAt;
        delete cleanedData.updatedAt;
        delete cleanedData.__v;
        
        // Ensure child parts and problems don't have _id either for cleaner json
        if (cleanedData.problems) {
          cleanedData.problems = cleanedData.problems.map((p: any) => {
            const { _id, ...rest } = p;
            return rest;
          });
        }
        if (cleanedData.parts) {
          cleanedData.parts = cleanedData.parts.map((part: any) => {
            const { _id, ...restPart } = part;
            if (restPart.problems) {
              restPart.problems = restPart.problems.map((p: any) => {
                const { _id, ...restP } = p;
                return restP;
              });
            }
            return restPart;
          });
        }
        
        setJsonText(JSON.stringify(cleanedData, null, 2));
      } else {
        setJsonText("");
      }
      setError("");
    }
  }, [isOpen, initialData]);

  const handleSubmit = async () => {
    setError("");
    let parsedData;
    
    try {
      parsedData = JSON.parse(jsonText);
    } catch (err) {
      setError("Invalid JSON format. Please check your syntax.");
      return;
    }

    if (!parsedData.title || typeof parsedData.title !== 'string') {
      setError("Track JSON must include a valid 'title' string.");
      return;
    }
    
    if (!parsedData.description || typeof parsedData.description !== 'string') {
      setError("Track JSON must include a valid 'description' string.");
      return;
    }

    setIsSubmitting(true);
    try {
      await onSubmit(parsedData);
      onClose();
    } catch (err: any) {
      setError(err.message || "Failed to save track. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <BaseModal
      isOpen={isOpen}
      onClose={onClose}
      modalId="track-modal"
      title={initialData ? "Edit Track" : "Add New Track"}
      subtitle="Paste the track JSON generated by the agent skill"
      icon={<FileJson className="w-5 h-5" />}
      maxWidthClass="max-w-3xl"
    >
      <div className="p-6">
        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-600 rounded-xl text-sm font-medium">
            {error}
          </div>
        )}
        <div className="mb-6">
          <label className="block text-sm font-bold text-neutral-700 mb-2">
            Track Configuration (JSON)
          </label>
          <textarea
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
            className="w-full h-[400px] p-4 bg-neutral-50 border border-neutral-200 rounded-xl font-mono text-sm focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none transition-all resize-y"
            placeholder={'{\n  "title": "Arrays & Hashing",\n  "description": "...",\n  "problems": []\n}'}
            spellCheck={false}
          />
        </div>
        
        <div className="flex justify-end gap-3 pt-4 border-t border-neutral-100">
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="px-5 py-2.5 text-sm font-bold text-neutral-600 hover:text-neutral-900 bg-white border border-neutral-200 hover:bg-neutral-50 rounded-xl transition-all disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={isSubmitting || !jsonText.trim()}
            className="px-5 py-2.5 text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl shadow-sm hover:shadow-md transition-all disabled:opacity-50"
          >
            {isSubmitting ? "Saving..." : "Save Track"}
          </button>
        </div>
      </div>
    </BaseModal>
  );
}
