name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # The URL is updated to point to your new dsapreparation Space
          git push https://jimfleax:$HF_TOKEN@huggingface.co/spaces/jimfleax/dsapreparation main
